trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '12-CI-CD-Pipelines/Azure-Devops/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    backendServiceArm: 'Visual Studio Professional Subscription(6854ec60-75fe-4b66-81b1-789cc0ef7063)'
    backendAzureRmResourceGroupName: 'myTempoRG'
    backendAzureRmStorageAccountName: 'johanrin'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '12-CI-CD-Pipelines/Azure-Devops/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    environmentServiceNameAzureRM: 'Visual Studio Professional Subscription(6854ec60-75fe-4b66-81b1-789cc0ef7063)'